# Load packages

In [1]:
import sys
sys.path.append('..')

In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from keras_layernorm_rnn import LayernormLSTM3

import pprint
pp = pprint.PrettyPrinter(indent=2)

# Parameters

In [3]:
num_samples = 2
timesteps = 3
embedding_dim = 4
units = 2

# Create dataset

In [4]:
x = np.random.random((num_samples, timesteps, embedding_dim))
y = np.random.random((num_samples, units))

# Modeling

In [5]:
model = Sequential([
     LayernormLSTM3(
         units, 
         use_layernorm=True,
         use_gamma=True,
         input_shape=(None, embedding_dim))
])

model.compile('rmsprop', 'mse')

# Training

In [6]:
model.fit(x, y, verbose=1)

Train on 2 samples
2/2 [==============================] - 6s 3s/sample - loss: 0.1929


# Results

In [7]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layernorm_lst_m3 (LayernormL (None, 2)                 64        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
# the scaling parameters for each multiplication (gamma)
model.layers[0].cell.get_weights()[12:]

[array([1.0031623 , 0.99683774], dtype=float32),
 array([0.99683785, 1.0031604 ], dtype=float32),
 array([1.0031623, 1.0031621], dtype=float32),
 array([0.99683774, 1.003162  ], dtype=float32)]

In [9]:
#cfg = model.layers[0].cell.get_config()
#pp.pprint(cfg)

In [10]:
cfg = model.get_config()
pp.pprint(cfg)

{ 'layers': [ { 'class_name': 'LayernormLSTM3',
                'config': { 'activation': 'tanh',
                            'batch_input_shape': (None, None, 4),
                            'bias_constraint': None,
                            'bias_initializer': { 'class_name': 'Zeros',
                                                  'config': {}},
                            'bias_regularizer': None,
                            'dropout': 0.0,
                            'dtype': 'float32',
                            'gamma_constraint': None,
                            'gamma_initializer': { '__passive_serialization__': True,
                                                   'class_name': 'Ones',
                                                   'config': {}},
                            'gamma_regularizer': None,
                            'go_backwards': False,
                            'implementation': 1,
                            'kernel_constraint': None,
          